### ISSUE TITLE
Static assets not prefixed

### ISSUE THREAD

**Issue by i001962** [moxystudio/gatsby-plugin-ipfs#13]
Looks like static images aren't getting prefixed.

Could it be as simple as adding static directory to gatsby-node.js line 74

```
const relativizeMiscAssetFiles = async () => {
    // Replaces all /__GATSBY_IPFS_PATH_PREFIX__/ strings to standard relative paths
    const paths = await globby(['public/**/*', '!public/**/*.html', '!public/**/*.js']);

```

**Comment by satazor** [comment]
I don't think the static folder needs to be processed unless there are HTML or JS files there referencing images to the same static folder.

It seems that the issue is that some static files, such as images, are being referenced within the src/ code but they aren't being handled:

```
// https://www.gatsbyjs.org/docs/static-folder/#referencing-your-static-asset
render() {
  // Note: this is an escape hatch and should be used sparingly!
  // Normally we recommend using `import` for getting asset URLs
  // as described in the “Importing Assets Directly Into Files” page.
  return <img src={'logo.png'} alt="Logo" />;
}
```

How can this plugin detect and parse these scenarios reliably without false positives? With `__GATSBY_IPFS_PATH_PREFIX__` is easy but it's not added in these situations.

**Comment by i001962** [comment]
Feel free to close this then. I had installed it on a starter that must have been using the escape hatch.

**Comment by satazor** [comment]
@i001962 While it's an escape hatch, I would prefer to have a solution for users, even if it's just a note in the README asking them to prefix with `__GATSBY_IPFS_PATH_PREFIX__`. Can you test if prefixing with `__GATSBY_IPFS_PATH_PREFIX__` when you referencing them works? If so, I would love a PR thats adds this note into the README ❤

**Comment by i001962** [comment]
@satazor ok will do but please confirm that something like this is what you are suggesting:


// https://www.gatsbyjs.org/docs/static-folder/#referencing-your-static-asset
render() {
  // Note: this is an escape hatch and should be used sparingly!
  // Normally we recommend using `import` for getting asset URLs
  // as described in the “Importing Assets Directly Into Files” page.
  return <img src={'__GATSBY_IPFS_PATH_PREFIX__logo.png'} alt="Logo" />;
}

**Comment by satazor** [comment]
Yep that’s it, I think you are missing a trailing slash.

**Comment by i001962** [comment]
@satazor that's why I was asking. 😆

**Comment by satazor** [comment]
@i001962 did the workaround solve the issue? Since you made a PR adding a note to the readme, I suppose it did?

**Comment by i001962** [comment]
Turns out static assets were not the issue. I will close this issue now as I have restated the issue in issue #14
